### ISSUE TITLE
There is no retry after a exception ReadTimeoutError

### ISSUE THREAD

**Issue by DimasDMM** [DevoInc/python-sdk#162]
**Problem**

I've encountered an exception ReadTimeoutError. Here's the full trace:
```python
Traceback (most recent call last):
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/myuser/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/myuser/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/myuser/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/myuser/.pyenv/versions/3.8.12/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/myuser/.pyenv/versions/3.8.12/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/myuser/.pyenv/versions/3.8.12/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='apiv2-us.devo.com', port=443): Read timed out. (read timeout=300)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/devo/api/client.py", line 549, in _make_request
    response = self.__request(payload)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/devo/api/client.py", line 577, in __request
    return requests.post("{}://{}".format(
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='apiv2-us.devo.com', port=443): Read timed out. (read timeout=300)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/myuser/Projects/myproject/src/runners/download/__main__.py", line 81, in <module>
    main(config, logger)
  File "/Users/myuser/Projects/myproject/src/runners/download/main.py", line 60, in main
    data = data_downloader.download_data(from_date=from_date, to_date=to_date)
  File "/Users/myuser/Projects/myproject/src/data/devo.py", line 103, in download_data
    for row in data_generator:
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/devo/api/client.py", line 463, in _return_string_stream
    (_, iterStringResponse, _) = self._make_request(payload)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/devo/api/client.py", line 571, in _make_request
    return raise_exception(error)
  File "/Users/myuser/Projects/myproject/venv/lib/python3.8/site-packages/devo/api/client.py", line 95, in raise_exception
    raise DevoClientException(_format_error(error_data, status=None))\
devo.api.client.DevoClientException: HTTPSConnectionPool(host='apiv2-us.devo.com', port=443): Read timed out. (read timeout=300): HTTPSConnectionPool(host='apiv2-us.devo.com', port=443): Read timed out. (read timeout=300)
```

**Code affected**

After digging a bit into the code, I found out that it retries the request only after one type of exception: https://github.com/DevoInc/python-sdk/blob/cdecb11740a49e6321e5587e7e00c19b0016827a/devo/api/client.py#L560
```python
except requests.exceptions.ConnectionError as error:
    tries += 1
    if tries > self.retries:
        return raise_exception(error)
    time.sleep(self.retry_delay * (2 ** (tries-1)))
except DevoClientException as error:
    if isinstance(error, DevoClientException):
        raise_exception(error.args[0])
    else:
        raise_exception(error)
except Exception as error:
    return raise_exception(error)
```

**Possible solution**

It would be better that other timeout errors are included in the retry. Here's the full list of exceptions: https://urllib3.readthedocs.io/en/stable/reference/urllib3.exceptions.html

Or just simply retry everything that it is not a Devo exception:
```python
except DevoClientException as error:
    if isinstance(error, DevoClientException):
        raise_exception(error.args[0])
    else:
        raise_exception(error)
except Exception as error:
    tries += 1
    if tries > self.retries:
        return raise_exception(error)
    time.sleep(self.retry_delay * (2 ** (tries-1)))
```

**Comment by JuanFranDevo** [comment]
Thanks @DimasDMM for taking the time and effort of creating the issue!

As described in [retries documentation](https://github.com/DevoInc/python-sdk/blob/master/docs/api/api.md#retries):
> The Client supports a retry mechanism for connectivity issues only

It is not expected to cover any other situation with retries. In fact, in version [4.0.0](https://github.com/DevoInc/python-sdk/blob/master/CHANGELOG.md#400---2022-08-05) the retries mechanism was disabled (retries attempts set to 0 by default). So the retry mechanism may be deprecated in the future. By design, it makes more sense for us to enable such a retry mechanism externally to the SDK.

This explanation does not mean, it is not going to be done. It is just the explanation on why it has been done that way, Please, let's open a discussion if this feature is required.

**Comment by JuanFranDevo** [comment]
For design reasons, the retry mechanism made more sense to be implemented on the developer side and not in SDK. Those mechanisms may force or restrict the behavior of the SDK making it less flexible or versatile.
In order to improve the information and feedback the developer has and allow him/her to make the right decision, error feedback has been enhanced and detailed during the last versions.

**Comment by JuanFranDevo** [comment]
For design reasons, the retry mechanism made more sense to be implemented on the developer side and not in SDK. Those mechanisms may force or restrict the behavior of the SDK making it less flexible or versatile.
In order to improve the information and feedback the developer has and allow him/her to make the right decision, error feedback has been enhanced and detailed during the last versions.

**Comment by JuanFranDevo** [comment]
For design reasons, the retry mechanism made more sense to be implemented on the developer side and not in SDK. Those mechanisms may force or restrict the behavior of the SDK making it less flexible or versatile.
In order to improve the information and feedback the developer has and allow him/her to make the right decision, error feedback has been enhanced and detailed during the last versions.

**Comment by DimasDMM** [comment]
Agree, closing this issue then
