### ISSUE TITLE
var "DEVO_API_TOKEN" variable available, but does not work, even "--env" argument was set for use env vars as configuration

### ISSUE THREAD

**Issue by sieferos** [DevoInc/python-sdk#88]
`devo-api query` does not allow to use "DEVO_API_TOKEN" from env var; does not work, even "--env" argument was set for use env vars as configuration:

```shell
( export DEVO_API_TOKEN="d41d8cd98f00b204e9800998ecf8427e" ; devo-api query \
--address "https://apiv2-es.devo.com/search/query" \
--env \
--no-stream \
--from "yesterday()" \
--to "today()" \
--query 'from my.app.foo.bar select * limit 1' \
--response csv )

Traceback (most recent call last):
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/devo/api/client.py", line 352, in _make_request
    headers=self._get_headers(payload),
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/devo/api/client.py", line 450, in _get_headers
    raise DevoClientException(_format_error(ERROR_MSGS['no_auth']))
devo.api.client.DevoClientException: {"msg": "Error Launching Query", "status": 500, "object": "Client dont have key&secret or auth token/jwt"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/logtrust/python3/venv_tf_kpis/bin/devo-api", line 8, in <module>
    sys.exit(cli())
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/devo/api/scripts/client_cli.py", line 84, in query
    process_response(reponse, config)
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/devo/api/scripts/client_cli.py", line 105, in process_response
    for item in response:
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/devo/api/client.py", line 319, in _return_stream
    response = self._make_request(payload)
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/devo/api/client.py", line 369, in _make_request
    raise_exception(error.args[0])
  File "/opt/logtrust/python3/venv_tf_kpis/lib/python3.7/site-packages/devo/api/client.py", line 42, in raise_exception
    raise DevoClientException(proc_json()(error))
devo.api.client.DevoClientException: {'msg': 'Error Launching Query', 'status': 500, 'object': 'Client dont have key&secret or auth token/jwt'}
```

**Comment by Worvast** [comment]
effectively with the inclusion of the use of token and jwt in the API, the use of those values ​​through ENV was not included.

Planned for the next hotfix soon
